CREATE TABLE IF NOT EXISTS asset_blobs (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  storage_provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  bucket_name VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  object_key VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  storage_version_id VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
  etag VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
  sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  mime_type VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ready',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_asset_blobs_location (storage_provider, bucket_name, object_key),
  KEY idx_asset_blobs_org_hash (organization_id, sha256, size_bytes),
  CONSTRAINT fk_asset_blobs_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT chk_asset_blobs_size CHECK (size_bytes > 0),
  CONSTRAINT chk_asset_blobs_status CHECK (status IN ('quarantine', 'ready', 'orphaned', 'deleted'))
);

CREATE TABLE IF NOT EXISTS assets (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_kind VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'processing',
  owner_system VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  latest_version BIGINT NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_assets_org_id (organization_id, id),
  KEY idx_assets_org_status (organization_id, status, updated_at),
  CONSTRAINT fk_assets_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT chk_assets_kind CHECK (asset_kind IN ('image', 'video', 'audio', 'document', 'text')),
  CONSTRAINT chk_assets_status CHECK (status IN ('processing', 'ready', 'quarantined', 'failed', 'archived', 'deleted')),
  CONSTRAINT chk_assets_latest_version CHECK (latest_version > 0)
);

CREATE TABLE IF NOT EXISTS asset_versions (
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version BIGINT NOT NULL,
  blob_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mime_type VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  width_pixels INT UNSIGNED NULL,
  height_pixels INT UNSIGNED NULL,
  duration_seconds DOUBLE NULL,
  fps DOUBLE NULL,
  codec VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  bitrate_bps BIGINT UNSIGNED NULL,
  audio_codec VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  audio_channels INT UNSIGNED NULL,
  audio_sample_rate INT UNSIGNED NULL,
  poster_frame_ref VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
  probe_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'not_required',
  probe_error VARCHAR(1024) NULL,
  provider_job_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  provider_output_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  project_context_version BIGINT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (organization_id, asset_id, version),
  UNIQUE KEY uq_asset_versions_blob (blob_id),
  KEY idx_asset_versions_org_hash (organization_id, sha256, size_bytes),
  CONSTRAINT fk_asset_versions_asset FOREIGN KEY (organization_id, asset_id) REFERENCES assets(organization_id, id),
  CONSTRAINT fk_asset_versions_blob FOREIGN KEY (blob_id) REFERENCES asset_blobs(id),
  CONSTRAINT chk_asset_versions_version CHECK (version > 0),
  CONSTRAINT chk_asset_versions_size CHECK (size_bytes > 0),
  CONSTRAINT chk_asset_versions_status CHECK (status IN ('processing', 'ready', 'quarantined', 'failed')),
  CONSTRAINT chk_asset_versions_source CHECK (source_type IN ('upload', 'provider_generated', 'imported', 'captured')),
  CONSTRAINT chk_asset_versions_probe_status CHECK (probe_status IN ('not_required', 'succeeded', 'failed'))
);

CREATE TABLE IF NOT EXISTS project_assets (
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_version BIGINT NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (organization_id, project_id, asset_id, asset_version),
  KEY idx_project_assets_list (organization_id, project_id, status, created_at),
  CONSTRAINT fk_project_assets_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_project_assets_version FOREIGN KEY (organization_id, asset_id, asset_version) REFERENCES asset_versions(organization_id, asset_id, version),
  CONSTRAINT chk_project_assets_status CHECK (status IN ('active', 'archived', 'removed'))
);

CREATE TABLE IF NOT EXISTS asset_features (
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_version BIGINT NOT NULL,
  schema_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  feature_version VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  hook_strength DOUBLE NOT NULL,
  product_visibility DOUBLE NOT NULL,
  scene_tags JSON NOT NULL,
  product_tags JSON NOT NULL,
  person_tags JSON NOT NULL,
  action_tags JSON NOT NULL,
  emotion_tags JSON NOT NULL,
  selling_points JSON NOT NULL,
  cta_presence BOOLEAN NOT NULL,
  similarity_group VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  similarity_risk VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  evidence JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (organization_id, project_id, asset_id, asset_version, feature_version),
  KEY idx_asset_features_project (organization_id, project_id, updated_at),
  CONSTRAINT fk_asset_features_project_asset FOREIGN KEY (organization_id, project_id, asset_id, asset_version) REFERENCES project_assets(organization_id, project_id, asset_id, asset_version),
  CONSTRAINT chk_asset_features_schema CHECK (schema_version = 'asset_feature_v1'),
  CONSTRAINT chk_asset_features_hook CHECK (hook_strength >= 0 AND hook_strength <= 1),
  CONSTRAINT chk_asset_features_product_visibility CHECK (product_visibility >= 0 AND product_visibility <= 1),
  CONSTRAINT chk_asset_features_similarity_risk CHECK (similarity_risk IN ('low', 'medium', 'high'))
);

CREATE TABLE IF NOT EXISTS upload_sessions (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  principal_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  principal_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'created',
  original_filename VARCHAR(512) NOT NULL,
  declared_mime_type VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  declared_size_bytes BIGINT UNSIGNED NOT NULL,
  declared_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  quarantine_provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quarantine_bucket VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quarantine_object_key VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_context_version BIGINT NOT NULL,
  target_asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_blob_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  trace_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  asset_version BIGINT NULL,
  error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  expires_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_upload_sessions_idempotency (organization_id, project_id, principal_kind, principal_id, idempotency_key),
  UNIQUE KEY uq_upload_sessions_quarantine (quarantine_bucket, quarantine_object_key),
  KEY idx_upload_sessions_expiry (status, expires_at),
  CONSTRAINT fk_upload_sessions_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT chk_upload_sessions_size CHECK (declared_size_bytes > 0),
  CONSTRAINT chk_upload_sessions_status CHECK (status IN ('created', 'uploaded', 'processing', 'succeeded', 'failed', 'expired'))
);

CREATE TABLE IF NOT EXISTS generated_intakes (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_job_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  output_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'queued',
  request_payload JSON NOT NULL,
  idempotency_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_blob_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  asset_version BIGINT NULL,
  error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_message VARCHAR(1024) NULL,
  retryable BOOLEAN NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  trace_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  lock_owner VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  locked_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_generated_intakes_output (organization_id, project_id, provider_job_id, output_id),
  UNIQUE KEY uq_generated_intakes_idempotency (organization_id, project_id, provider_job_id, output_id, idempotency_key),
  KEY idx_generated_intakes_claim (organization_id, status, available_at, created_at),
  KEY idx_generated_intakes_stale (organization_id, status, locked_at, created_at),
  CONSTRAINT fk_generated_intakes_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT chk_generated_intakes_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed'))
);

CREATE TABLE IF NOT EXISTS assets_outbox (
  event_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  aggregate_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  aggregate_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  aggregate_version BIGINT NOT NULL,
  payload JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  published_at DATETIME(6) NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error VARCHAR(1024) NULL,
  KEY idx_assets_outbox_unpublished (published_at, created_at),
  KEY idx_assets_outbox_aggregate (organization_id, aggregate_type, aggregate_id, aggregate_version)
);
