CREATE TABLE platform_skill_run_attempts (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NOT NULL,
  skill_run_id VARCHAR(96) NOT NULL,
  attempt_no INT NOT NULL,
  purpose VARCHAR(32) NOT NULL,
  provider_code VARCHAR(64) NOT NULL,
  model_alias VARCHAR(255) NULL,
  model_version VARCHAR(128) NULL,
  route_revision_id VARCHAR(96) NULL,
  response_mode VARCHAR(24) NULL,
  api_mode VARCHAR(24) NULL,
  background BOOLEAN NOT NULL DEFAULT FALSE,
  prompt_version VARCHAR(96) NULL,
  input_tokens BIGINT NULL,
  output_tokens BIGINT NULL,
  total_tokens BIGINT NULL,
  latency_ms BIGINT NOT NULL,
  validation_passed BOOLEAN NOT NULL,
  validation_errors JSON NULL,
  output_hash CHAR(64) NULL,
  created_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_skill_run_attempt_scope (organization_id, project_id, skill_run_id, attempt_no),
  KEY idx_skill_run_attempt_run (organization_id, project_id, skill_run_id)
);
