CREATE TABLE platform_jobs (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  kind VARCHAR(128) NOT NULL,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NULL,
  status VARCHAR(16) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  result_type VARCHAR(128) NULL,
  result_id VARCHAR(128) NULL,
  result_version BIGINT NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  retryable BOOLEAN NULL,
  cancellable BOOLEAN NOT NULL DEFAULT TRUE,
  version BIGINT NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(255) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 1,
  available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  lock_owner VARCHAR(128) NULL,
  locked_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_platform_jobs_idempotency (organization_id, idempotency_key),
  KEY idx_platform_jobs_claim (status, available_at, created_at)
);
