CREATE TABLE remix_render_jobs (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NOT NULL,
  principal_kind VARCHAR(32) NOT NULL,
  principal_id VARCHAR(128) NOT NULL,
  plan_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  target_format VARCHAR(16) NOT NULL,
  target_quality VARCHAR(32) NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  input_snapshot JSON NOT NULL,
  requires_review BOOLEAN NOT NULL DEFAULT FALSE,
  quality_report_id VARCHAR(96) NULL,
  output_asset_id VARCHAR(96) NULL,
  output_asset_version BIGINT NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_remix_render_idempotency (organization_id, project_id, principal_kind, principal_id, idempotency_key),
  KEY idx_remix_render_plan (organization_id, project_id, plan_id),
  KEY idx_remix_render_status (status, updated_at)
);

CREATE TABLE remix_quality_reports (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NOT NULL,
  principal_kind VARCHAR(32) NOT NULL,
  principal_id VARCHAR(128) NOT NULL,
  render_job_id VARCHAR(96) NOT NULL,
  output_asset_id VARCHAR(96) NULL,
  output_asset_version BIGINT NULL,
  verdict VARCHAR(32) NOT NULL,
  score DECIMAL(5,4) NOT NULL,
  dimensions JSON NOT NULL,
  issues JSON NOT NULL,
  evidence JSON NOT NULL,
  repair_suggestions JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_remix_quality_render_job (organization_id, project_id, render_job_id),
  KEY idx_remix_quality_verdict (organization_id, project_id, verdict, created_at)
);
