CREATE TABLE provider_jobs (
  id VARCHAR(96) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NOT NULL,
  principal_kind VARCHAR(16) NOT NULL,
  principal_id VARCHAR(96) NOT NULL,
  operation_name VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  kind VARCHAR(128) NOT NULL,
  model_alias VARCHAR(255) NOT NULL,
  source_system VARCHAR(96) NULL,
  source_task_id VARCHAR(96) NULL,
  project_context_version BIGINT NOT NULL,
  execution_status VARCHAR(16) NOT NULL,
  provider_status VARCHAR(32) NOT NULL,
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  provider_code VARCHAR(64) NULL,
  model_version VARCHAR(255) NULL,
  external_task_id VARCHAR(255) NULL,
  input_payload JSON NOT NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  retryable BOOLEAN NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_provider_jobs_idempotency (organization_id, project_id, principal_kind, principal_id, operation_name, idempotency_key),
  KEY idx_provider_jobs_scope (organization_id, project_id, created_at),
  KEY idx_provider_jobs_status (execution_status, provider_status, updated_at),
  KEY idx_provider_jobs_external_task (provider_code, external_task_id)
);
