-- Insights owns Miyun connection state, controlled product queries, crawl jobs,
-- the current material projection, append-only data-card snapshots, and handoffs.
-- Third-party protocol DTOs remain in internal/integrations/crawler; authorized
-- media import idempotency remains in the Assets-owned asset_external_imports.

CREATE TABLE IF NOT EXISTS insight_miyun_connections (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  session_ciphertext VARBINARY(4096) NOT NULL,
  session_key_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  session_expires_at DATETIME(6) NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'unverified',
  last_verified_at DATETIME(6) NULL,
  last_successful_request_at DATETIME(6) NULL,
  last_error_kind VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  last_error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  last_error_at DATETIME(6) NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_connections_scope (organization_id, id),
  UNIQUE KEY uq_insight_miyun_connections_project_scope (organization_id, project_id, id),
  KEY idx_insight_miyun_connections_project (organization_id, project_id, status, updated_at),
  CONSTRAINT fk_insight_miyun_connections_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT chk_insight_miyun_connections_status CHECK (status IN ('unverified', 'ready', 'auth_required', 'disabled')),
  CONSTRAINT chk_insight_miyun_connections_version CHECK (version > 0),
  CONSTRAINT chk_insight_miyun_connections_ciphertext CHECK (OCTET_LENGTH(session_ciphertext) > 0),
  CONSTRAINT chk_insight_miyun_connections_error_pair CHECK ((last_error_kind IS NULL AND last_error_code IS NULL) OR (last_error_kind IS NOT NULL AND last_error_code IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS insight_miyun_product_profiles (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  connection_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  category_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  category_name VARCHAR(255) NOT NULL DEFAULT '',
  keywords JSON NOT NULL,
  material_content_types JSON NOT NULL,
  window_start DATE NOT NULL,
  window_end DATE NOT NULL,
  project_context_version BIGINT NOT NULL,
  product_asset_refs JSON NOT NULL,
  knowledge_document_ids JSON NOT NULL,
  rule_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  confirmed_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  confirmed_at DATETIME(6) NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_product_profiles_scope (organization_id, id),
  UNIQUE KEY uq_insight_miyun_product_profiles_project_scope (organization_id, project_id, id),
  KEY idx_insight_miyun_product_profiles_project (organization_id, project_id, status, updated_at),
  CONSTRAINT fk_insight_miyun_product_profiles_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_miyun_product_profiles_connection FOREIGN KEY (organization_id, project_id, connection_id) REFERENCES insight_miyun_connections(organization_id, project_id, id),
  CONSTRAINT chk_insight_miyun_product_profiles_status CHECK (status IN ('draft', 'confirmed', 'superseded')),
  CONSTRAINT chk_insight_miyun_product_profiles_version CHECK (version > 0),
  CONSTRAINT chk_insight_miyun_product_profiles_context CHECK (project_context_version > 0),
  CONSTRAINT chk_insight_miyun_product_profiles_window CHECK (window_start <= window_end),
  CONSTRAINT chk_insight_miyun_product_profiles_confirmed CHECK (status <> 'confirmed' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS insight_miyun_crawl_jobs (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  connection_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  product_profile_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  operation VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  query_schema_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  query_snapshot JSON NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'queued',
  completed_pages BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discovered_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  deduplicated_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  downloaded_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  failed_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cooldown_until DATETIME(6) NULL,
  last_error_kind VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  last_error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_crawl_jobs_scope (organization_id, id),
  UNIQUE KEY uq_insight_miyun_crawl_jobs_project_scope (organization_id, project_id, id),
  KEY idx_insight_miyun_crawl_jobs_claim (organization_id, project_id, status, cooldown_until, created_at),
  CONSTRAINT fk_insight_miyun_crawl_jobs_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_miyun_crawl_jobs_connection FOREIGN KEY (organization_id, project_id, connection_id) REFERENCES insight_miyun_connections(organization_id, project_id, id),
  CONSTRAINT fk_insight_miyun_crawl_jobs_profile FOREIGN KEY (organization_id, project_id, product_profile_id) REFERENCES insight_miyun_product_profiles(organization_id, project_id, id),
  CONSTRAINT chk_insight_miyun_crawl_jobs_status CHECK (status IN ('queued', 'running', 'cooling_down', 'auth_required', 'partial', 'succeeded', 'failed', 'cancelled')),
  CONSTRAINT chk_insight_miyun_crawl_jobs_operation CHECK (operation IN ('product', 'cid')),
  CONSTRAINT chk_insight_miyun_crawl_jobs_version CHECK (version > 0),
  CONSTRAINT chk_insight_miyun_crawl_jobs_cooldown CHECK (status <> 'cooling_down' OR cooldown_until IS NOT NULL),
  CONSTRAINT chk_insight_miyun_crawl_jobs_error_pair CHECK ((last_error_kind IS NULL AND last_error_code IS NULL) OR (last_error_kind IS NOT NULL AND last_error_code IS NOT NULL))
);

-- Existing insight_assets has an organization-scoped identity key. The extra
-- composite key lets Miyun current projections enforce Project isolation too.
ALTER TABLE insight_assets
  ADD UNIQUE KEY uq_insight_assets_project_scope (organization_id, project_id, id);

CREATE TABLE IF NOT EXISTS insight_miyun_materials (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  first_seen_crawl_job_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  miyun_material_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  resource_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  source_ref VARCHAR(1024) NOT NULL DEFAULT '',
  title VARCHAR(512) NOT NULL DEFAULT '',
  selection_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'discovered',
  import_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'pending',
  external_import_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  platform_asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  platform_asset_version BIGINT NULL,
  insight_asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_materials_scope (organization_id, id),
  UNIQUE KEY uq_insight_miyun_materials_project_scope (organization_id, project_id, id),
  UNIQUE KEY uq_insight_miyun_materials_source (organization_id, project_id, miyun_material_id),
  KEY idx_insight_miyun_materials_job (organization_id, project_id, first_seen_crawl_job_id, updated_at),
  KEY idx_insight_miyun_materials_import (organization_id, project_id, import_status, updated_at),
  CONSTRAINT fk_insight_miyun_materials_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_miyun_materials_job FOREIGN KEY (organization_id, project_id, first_seen_crawl_job_id) REFERENCES insight_miyun_crawl_jobs(organization_id, project_id, id),
  CONSTRAINT fk_insight_miyun_materials_external_import FOREIGN KEY (organization_id, project_id, external_import_id) REFERENCES asset_external_imports(organization_id, project_id, id),
  CONSTRAINT fk_insight_miyun_materials_asset_version FOREIGN KEY (organization_id, platform_asset_id, platform_asset_version) REFERENCES asset_versions(organization_id, asset_id, version),
  CONSTRAINT fk_insight_miyun_materials_project_asset FOREIGN KEY (organization_id, project_id, platform_asset_id, platform_asset_version) REFERENCES project_assets(organization_id, project_id, asset_id, asset_version),
  CONSTRAINT fk_insight_miyun_materials_insight_asset FOREIGN KEY (organization_id, project_id, insight_asset_id) REFERENCES insight_assets(organization_id, project_id, id),
  CONSTRAINT chk_insight_miyun_materials_selection CHECK (selection_status IN ('discovered', 'confirmed', 'rejected')),
  CONSTRAINT chk_insight_miyun_materials_import CHECK (import_status IN ('pending', 'downloading', 'imported', 'deduplicated', 'failed', 'skipped')),
  CONSTRAINT chk_insight_miyun_materials_version CHECK (version > 0),
  CONSTRAINT chk_insight_miyun_materials_asset_pair CHECK ((platform_asset_id IS NULL AND platform_asset_version IS NULL) OR (platform_asset_id IS NOT NULL AND platform_asset_version IS NOT NULL)),
  CONSTRAINT chk_insight_miyun_materials_insight_asset_pair CHECK (insight_asset_id IS NULL OR (platform_asset_id IS NOT NULL AND platform_asset_version IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS insight_miyun_material_snapshots (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  material_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  crawl_job_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schema_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  captured_at DATETIME(6) NOT NULL,
  first_published_at DATETIME(6) NULL,
  last_published_at DATETIME(6) NULL,
  delivery_days BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cumulative_impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
  related_ads BIGINT UNSIGNED NOT NULL DEFAULT 0,
  related_creators BIGINT UNSIGNED NOT NULL DEFAULT 0,
  material_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
  views BIGINT UNSIGNED NOT NULL DEFAULT 0,
  likes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  comments BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shares BIGINT UNSIGNED NOT NULL DEFAULT 0,
  saves BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sanitized_raw JSON NULL,
  created_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_material_snapshots_scope (organization_id, id),
  KEY idx_insight_miyun_material_snapshots_history (organization_id, project_id, material_id, captured_at, id),
  CONSTRAINT fk_insight_miyun_material_snapshots_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_miyun_material_snapshots_material FOREIGN KEY (organization_id, project_id, material_id) REFERENCES insight_miyun_materials(organization_id, project_id, id),
  CONSTRAINT fk_insight_miyun_material_snapshots_job FOREIGN KEY (organization_id, project_id, crawl_job_id) REFERENCES insight_miyun_crawl_jobs(organization_id, project_id, id),
  CONSTRAINT chk_insight_miyun_material_snapshots_score CHECK (material_score >= 0),
  CONSTRAINT chk_insight_miyun_material_snapshots_dates CHECK ((first_published_at IS NULL AND last_published_at IS NULL) OR (first_published_at IS NOT NULL AND last_published_at IS NOT NULL AND first_published_at <= last_published_at))
);

CREATE TABLE IF NOT EXISTS insight_miyun_handoffs (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_material_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  product_profile_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'exporting',
  manifest_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  parameter_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  product_files_snapshot JSON NOT NULL,
  source_snapshot JSON NOT NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,

  UNIQUE KEY uq_insight_miyun_handoffs_scope (organization_id, id),
  UNIQUE KEY uq_insight_miyun_handoffs_project_scope (organization_id, project_id, id),
  KEY idx_insight_miyun_handoffs_project (organization_id, project_id, status, updated_at),
  CONSTRAINT fk_insight_miyun_handoffs_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_miyun_handoffs_material FOREIGN KEY (organization_id, project_id, source_material_id) REFERENCES insight_miyun_materials(organization_id, project_id, id),
  CONSTRAINT fk_insight_miyun_handoffs_profile FOREIGN KEY (organization_id, project_id, product_profile_id) REFERENCES insight_miyun_product_profiles(organization_id, project_id, id),
  CONSTRAINT chk_insight_miyun_handoffs_status CHECK (status IN ('exporting', 'exported', 'delivered', 'returned', 'failed')),
  CONSTRAINT chk_insight_miyun_handoffs_version CHECK (version > 0)
);
