CREATE TABLE insight_miyun_handoff_returns (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  handoff_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  handoff_version BIGINT NOT NULL,
  manifest_version VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  parameter_version VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  product_profile_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  upload_idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  upload_request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  filename VARCHAR(512) NULL,
  asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  asset_version BIGINT NULL,
  mime_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  size_bytes BIGINT NULL,
  insight_asset_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  uploaded_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  uploaded_at DATETIME(6) NULL,
  failure_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  mark_idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  mark_request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  returned_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  returned_at DATETIME(6) NULL,
  version BIGINT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_insight_miyun_return_idem (organization_id, project_id, handoff_id, idempotency_key),
  KEY idx_insight_miyun_returns_handoff (organization_id, project_id, handoff_id, created_at),
  CONSTRAINT chk_insight_miyun_return_status CHECK (status IN ('created','uploaded','failed','returned')),
  CONSTRAINT chk_insight_miyun_return_version CHECK (version > 0 AND handoff_version > 0),
  CONSTRAINT chk_insight_miyun_return_size CHECK (size_bytes IS NULL OR size_bytes > 0),
  CONSTRAINT fk_insight_miyun_return_handoff FOREIGN KEY (organization_id, project_id, handoff_id) REFERENCES insight_miyun_handoffs(organization_id, project_id, id)
);
