CREATE TABLE insight_reports (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  execution_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  delivery_mode VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  evidence_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  evidence_summary VARCHAR(1000) NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  summary VARCHAR(2000) NOT NULL,
  findings JSON NOT NULL,
  version BIGINT NOT NULL,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  confirmed_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  confirmed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_insight_reports_execution (organization_id, execution_id),
  UNIQUE KEY uq_insight_reports_scope (organization_id, id),
  KEY idx_insight_reports_project (organization_id, project_id, updated_at),
  CONSTRAINT fk_insight_reports_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT chk_insight_reports_version CHECK (version > 0),
  CONSTRAINT chk_insight_reports_status CHECK (status IN ('draft', 'confirmed'))
);

CREATE TABLE insight_experiences (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  report_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_execution_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_evidence_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  conclusion VARCHAR(2000) NOT NULL,
  conditions JSON NOT NULL,
  counterexamples JSON NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version BIGINT NOT NULL,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_insight_experiences_report (organization_id, report_id),
  UNIQUE KEY uq_insight_experiences_scope (organization_id, id),
  KEY idx_insight_experiences_project (organization_id, project_id, updated_at),
  CONSTRAINT fk_insight_experiences_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT fk_insight_experiences_report FOREIGN KEY (organization_id, report_id) REFERENCES insight_reports(organization_id, id),
  CONSTRAINT chk_insight_experiences_version CHECK (version > 0),
  CONSTRAINT chk_insight_experiences_status CHECK (status IN ('confirmed'))
);
