package provider

import (
	"bytes"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"strings"

	"github.com/shikanon/cookies/internal/platform/assets"
	"github.com/shikanon/cookies/internal/platform/contract"
)

// ObjectOutputHandleStore keeps generated bytes out of MySQL for deployed
// adapter_gateway traffic. MySQL retains only scoped integrity metadata and a
// private object location.
type ObjectOutputHandleStore struct {
	DB     *sql.DB
	Blobs  assets.BlobStore
	Bucket string
}

func (s ObjectOutputHandleStore) Put(ctx context.Context, project contract.ProjectRef, ref contract.ProviderOutputRef, contents []byte) error {
	if s.DB == nil || s.Blobs == nil || strings.TrimSpace(s.Bucket) == "" {
		return fmt.Errorf("MySQL database, blob store, and Provider output bucket are required")
	}
	if err := project.Validate(); err != nil {
		return err
	}
	if err := ref.Validate(); err != nil {
		return err
	}
	if len(contents) == 0 || int64(len(contents)) != ref.DeclaredSizeBytes || ref.DeclaredSHA256 == nil {
		return fmt.Errorf("provider output contents do not match declared metadata")
	}
	digest := sha256.Sum256(contents)
	actualSHA := hex.EncodeToString(digest[:])
	if actualSHA != *ref.DeclaredSHA256 {
		return fmt.Errorf("provider output contents do not match declared SHA-256")
	}
	key := providerOutputObjectKey(project, ref)
	info, err := s.Blobs.Put(ctx, s.Bucket, key, bytes.NewReader(contents), int64(len(contents)), ref.DeclaredMIMEType)
	if err != nil {
		return err
	}
	_, err = s.DB.ExecContext(ctx, `INSERT INTO provider_job_output_handles (
		provider_job_id, output_id, organization_id, project_id, provider_code,
		retrieval_expires_at, mime_type, size_bytes, sha256, contents,
		storage_provider, storage_bucket, storage_key, storage_version_id
	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, NULLIF(?, ''))
	ON DUPLICATE KEY UPDATE organization_id = VALUES(organization_id), project_id = VALUES(project_id),
		provider_code = VALUES(provider_code), retrieval_expires_at = VALUES(retrieval_expires_at),
		mime_type = VALUES(mime_type), size_bytes = VALUES(size_bytes), sha256 = VALUES(sha256), contents = NULL,
		storage_provider = VALUES(storage_provider), storage_bucket = VALUES(storage_bucket),
		storage_key = VALUES(storage_key), storage_version_id = VALUES(storage_version_id)`,
		ref.ProviderJobID, ref.OutputID, project.OrganizationID, project.ProjectID, ref.ProviderCode,
		ref.RetrievalExpiresAt, ref.DeclaredMIMEType, ref.DeclaredSizeBytes, actualSHA,
		info.Provider, info.Bucket, info.Key, info.VersionID)
	if err != nil {
		_ = s.Blobs.Delete(context.WithoutCancel(ctx), info.ObjectLocation)
	}
	return err
}

func (s ObjectOutputHandleStore) Open(ctx context.Context, project contract.ProjectRef, ref contract.ProviderOutputRef) (io.ReadCloser, contract.OutputMetadata, error) {
	if s.DB == nil || s.Blobs == nil {
		return nil, contract.OutputMetadata{}, fmt.Errorf("MySQL database and blob store are required")
	}
	if err := project.Validate(); err != nil {
		return nil, contract.OutputMetadata{}, err
	}
	if err := ref.Validate(); err != nil {
		return nil, contract.OutputMetadata{}, err
	}
	var location assets.ObjectLocation
	var mimeType, sha string
	var size int64
	err := s.DB.QueryRowContext(ctx, `SELECT storage_provider, storage_bucket, storage_key, COALESCE(storage_version_id, ''),
			mime_type, size_bytes, sha256
		FROM provider_job_output_handles
		WHERE provider_job_id = ? AND output_id = ? AND organization_id = ? AND project_id = ?
			AND provider_code = ? AND retrieval_expires_at > UTC_TIMESTAMP(6) AND contents IS NULL`,
		ref.ProviderJobID, ref.OutputID, project.OrganizationID, project.ProjectID, ref.ProviderCode,
	).Scan(&location.Provider, &location.Bucket, &location.Key, &location.VersionID, &mimeType, &size, &sha)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, contract.OutputMetadata{}, ErrOutputHandleNotFound
	}
	if err != nil {
		return nil, contract.OutputMetadata{}, err
	}
	if mimeType != ref.DeclaredMIMEType || size != ref.DeclaredSizeBytes || (ref.DeclaredSHA256 != nil && sha != *ref.DeclaredSHA256) {
		return nil, contract.OutputMetadata{}, fmt.Errorf("provider output handle metadata mismatch")
	}
	stream, info, err := s.Blobs.Open(ctx, location)
	if err != nil {
		return nil, contract.OutputMetadata{}, err
	}
	if info.SizeBytes != size || info.MIMEType != mimeType {
		_ = stream.Close()
		return nil, contract.OutputMetadata{}, fmt.Errorf("provider output object metadata mismatch")
	}
	return stream, contract.OutputMetadata{MIMEType: mimeType, SizeBytes: size, SHA256: sha}, nil
}

func (s ObjectOutputHandleStore) Delete(ctx context.Context, organizationID contract.OrganizationID, projectID contract.ProjectID, providerJobID, outputID string) error {
	if s.DB == nil || s.Blobs == nil {
		return fmt.Errorf("MySQL database and blob store are required")
	}
	var location assets.ObjectLocation
	err := s.DB.QueryRowContext(ctx, `SELECT storage_provider, storage_bucket, storage_key, COALESCE(storage_version_id, '')
		FROM provider_job_output_handles
		WHERE provider_job_id = ? AND output_id = ? AND organization_id = ? AND project_id = ? AND contents IS NULL`,
		providerJobID, outputID, organizationID, projectID,
	).Scan(&location.Provider, &location.Bucket, &location.Key, &location.VersionID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}
	if err != nil {
		return err
	}
	if err := s.Blobs.Delete(ctx, location); err != nil {
		return err
	}
	_, err = s.DB.ExecContext(ctx, `DELETE FROM provider_job_output_handles
		WHERE provider_job_id = ? AND output_id = ? AND organization_id = ? AND project_id = ?`,
		providerJobID, outputID, organizationID, projectID)
	return err
}

func providerOutputObjectKey(project contract.ProjectRef, ref contract.ProviderOutputRef) string {
	digest := sha256.Sum256([]byte(strings.Join([]string{
		string(project.OrganizationID), string(project.ProjectID), ref.ProviderJobID, ref.OutputID,
	}, "\x00")))
	return "provider-output/" + hex.EncodeToString(digest[:])
}
