CREATE TABLE delivery_controlled_change_sets (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  binding_json JSON NOT NULL,
  action VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  budget_limit_minor BIGINT NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version BIGINT NOT NULL,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_delivery_controlled_change_set_scope (organization_id, project_id, id),
  UNIQUE KEY uq_delivery_controlled_change_set_object (organization_id, project_id, canonical_hash),
  KEY idx_delivery_controlled_change_set_status (organization_id, project_id, status, updated_at),
  CONSTRAINT fk_delivery_controlled_change_set_project FOREIGN KEY (organization_id, project_id) REFERENCES projects(organization_id, id),
  CONSTRAINT chk_delivery_controlled_change_set_action CHECK (action IN ('create_project_and_promotions')),
  CONSTRAINT chk_delivery_controlled_change_set_budget CHECK (budget_limit_minor >= 0 AND currency = 'CNY'),
  CONSTRAINT chk_delivery_controlled_change_set_status CHECK (status IN ('ready_for_approval','approved','rejected','executing','executed','invalidated')),
  CONSTRAINT chk_delivery_controlled_change_set_version CHECK (version > 0)
);

CREATE TABLE delivery_remote_write_approvals (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  controlled_change_set_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  controlled_change_set_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  binding_json JSON NOT NULL,
  action VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  budget_limit_minor BIGINT NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  action_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  approved_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  approved_at DATETIME(6) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_delivery_remote_write_approval_scope (organization_id, project_id, id),
  UNIQUE KEY uq_delivery_remote_write_approval_change_set (organization_id, project_id, controlled_change_set_id),
  CONSTRAINT fk_delivery_remote_write_approval_change_set FOREIGN KEY (organization_id, project_id, controlled_change_set_id) REFERENCES delivery_controlled_change_sets(organization_id, project_id, id),
  CONSTRAINT chk_delivery_remote_write_approval_authority CHECK (action = 'create_project_and_promotions' AND scope = 'controlled_remote_write'),
  CONSTRAINT chk_delivery_remote_write_approval_budget CHECK (budget_limit_minor >= 0 AND currency = 'CNY'),
  CONSTRAINT chk_delivery_remote_write_approval_expiry CHECK (expires_at > approved_at)
);

CREATE TABLE delivery_controlled_executions (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  controlled_change_set_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_write_approval_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  computer_use_run_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version BIGINT NOT NULL,
  created_by VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_delivery_controlled_execution_scope (organization_id, project_id, id),
  UNIQUE KEY uq_delivery_controlled_execution_change_set (organization_id, project_id, controlled_change_set_id),
  UNIQUE KEY uq_delivery_controlled_execution_run (organization_id, project_id, computer_use_run_id),
  CONSTRAINT fk_delivery_controlled_execution_change_set FOREIGN KEY (organization_id, project_id, controlled_change_set_id) REFERENCES delivery_controlled_change_sets(organization_id, project_id, id),
  CONSTRAINT fk_delivery_controlled_execution_approval FOREIGN KEY (organization_id, project_id, remote_write_approval_id) REFERENCES delivery_remote_write_approvals(organization_id, project_id, id),
  CONSTRAINT chk_delivery_controlled_execution_status CHECK (status IN ('pending','running','succeeded','failed','partial','result_unknown','cancelled')),
  CONSTRAINT chk_delivery_controlled_execution_version CHECK (version > 0)
);

ALTER TABLE delivery_executions
  ADD COLUMN computer_use_run_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  ADD UNIQUE KEY uq_delivery_execution_computer_use_run (organization_id, project_id, computer_use_run_id);

CREATE TABLE delivery_platform_entity_mappings (
  id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  organization_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  account_reference_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  plan_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  configuration_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  business_execution_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  computer_use_run_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  internal_object_kind VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  internal_object_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  platform_object_kind VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  platform_object_id VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NULL,
  platform_status VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  result_evidence_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  list_evidence_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version BIGINT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_delivery_platform_mapping_scope (organization_id, project_id, id),
  UNIQUE KEY uq_delivery_platform_mapping_internal (organization_id, project_id, account_reference_id, internal_object_kind, internal_object_id),
  UNIQUE KEY uq_delivery_platform_mapping_external (organization_id, project_id, account_reference_id, platform_object_kind, platform_object_id),
  KEY idx_delivery_platform_mapping_run (organization_id, project_id, computer_use_run_id),
  CONSTRAINT fk_delivery_platform_mapping_execution FOREIGN KEY (organization_id, project_id, business_execution_id) REFERENCES delivery_controlled_executions(organization_id, project_id, id),
  CONSTRAINT chk_delivery_platform_mapping_status CHECK (status IN ('pending_verification','confirmed')),
  CONSTRAINT chk_delivery_platform_mapping_version CHECK (version > 0),
  CONSTRAINT chk_delivery_platform_mapping_confirmation CHECK (status <> 'confirmed' OR (platform_object_id IS NOT NULL AND platform_status IS NOT NULL AND result_evidence_id IS NOT NULL AND list_evidence_id IS NOT NULL))
);
